name: Daily Gemini to Telegram Poster

on:
  schedule:
    - cron: '0 7 * * *'
  
  workflow_dispatch:

jobs:
  build-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ЭТОТ БЛОК НУЖНО ПРОВЕРИТЬ ОСОБЕННО ВНИМАТЕЛЬНО
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --no-cache-dir -r requirements.txt

      - name: Run Python script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: python main.py
